### ISSUE TITLE
How to compile this project

### ISSUE THREAD

**Issue by izengpan** [rising-turtle/graph_slam#1]
hello, the project seems very outstanding.
But I don't know how to compile it and see the performance of it.
Looking forward to your reply~

**Comment by izengpan** [comment]
And when I try to catkin_make the whole file, it seems that many files are missing, such as **sparse_feature_vo.h** and **camera_node_ba.h**.

Besides, I can't find these files in your other work.

**Comment by rising-turtle** [comment]
Hi @izengpan 
Please check the code in https://github.com/rising-turtle/visual_odometry, where the sparse_feature_vo.h and camera_node_ba.h exist. Note that the visual_odometry was developed based on OpenCV 2.4. 

Best,

**Comment by rising-turtle** [comment]
I am working on to integrate these projects together, into one that is more clear and easy to compile. I will make it depend on OpenCV 3.0 with fewer dependencies. Will public it when it's done.

**Comment by izengpan** [comment]
Got it.
Thanks for your reply~
