### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by JunlinSong** [rising-turtle/graph_slam#2]
Hello, I'm interested in your work. Can you provide relevant data files so that the program can run normally?

**Comment by rising-turtle** [comment]
Sorry for the late reply, two datasets can be available in the link. https://drive.google.com/drive/u/0/folders/1dqFwnTyBVjMo_nOrANsVVzr0sP7EGw0z 
BTW, this project was developed based on OpenCV 2.4, which was not compatible with the ROS version Kinetic. So I have gradually move it to another repository https://github.com/rising-turtle/pavio. It is almost identical to graph_slam, yet more clear and straightforward.

**Comment by JunlinSong** [comment]
Thank you for your reply, but this link can't be opened. Can you provide a new way to download it ?




------------------ 原始邮件 ------------------
发件人: "He Zhang"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 凌晨4:43
收件人: "rising-turtle/graph_slam"<graph_slam@noreply.github.com>;
抄送: "DFS"<2716554115@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rising-turtle/graph_slam] How to run this project (#2)




Sorry for the late reply, two datasets can be available in the link. https://drive.google.com/drive/u/0/folders/1dqFwnTyBVjMo_nOrANsVVzr0sP7EGw0z
 BTW, this project was developed based on OpenCV 2.4, which was not compatible with the ROS version Kinetic. So I have gradually move it to another repository https://github.com/rising-turtle/pavio. It is almost identical to graph_slam, yet more clear and straightforward.

**Comment by rising-turtle** [comment]
@wlwsjl Can you leave your email address so I can directly email it to you?

**Comment by JunlinSong** [comment]
That would be great！My email address is 2716554115@qq.com




------------------ 原始邮件 ------------------
发件人: "He Zhang"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 凌晨4:13
收件人: "rising-turtle/graph_slam"<graph_slam@noreply.github.com>;
抄送: "DFS"<2716554115@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [rising-turtle/graph_slam] How to run this project (#2)




@wlwsjl Can you leave your email address so I can directly email it to you?

**Comment by rising-turtle** [comment]
@wlwsjl sent, please check.

**Comment by JunlinSong** [comment]
I am sorry to bother you again. I still can't open ~





------------------ 原始邮件 ------------------
发件人: "He Zhang"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 凌晨2:00
收件人: "rising-turtle/graph_slam"<graph_slam@noreply.github.com>;
抄送: "DFS"<2716554115@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [rising-turtle/graph_slam] How to run this project (#2)




@wlwsjl sent, please check.

**Comment by JunlinSong** [comment]
![捕获](https://user-images.githubusercontent.com/25876543/65818607-8c8a3780-e245-11e9-9881-13ac0c10c14b.PNG)

**Comment by rising-turtle** [comment]
@wlwsjl I will resend it using another email.

**Comment by JunlinSong** [comment]
Thank you very much ~

**Comment by JunlinSong** [comment]
Do you have a compilation tutorial for the project？Which packages does this project depend on？
